### PR TITLE
added helper function to get modification time from git

### LINKED ISSUE #265: Blog post publication date
Currently the blog post publication date is set on the day the blog post is created, but we should actually move this to the date when the post is merged and published on the Zeus site.

### PR DESCRIPTION
**Pull request by JensTimmerman**
fixes #265

### CODE REVIEW

**Comment by JensTimmerman** [comment]
Screenshot 2020-10-12 at 23 48 53

**Comment by JensTimmerman** [comment]
804c0b1 shows 
Screenshot 2020-10-13 at 00 06 04

**Comment by JensTimmerman** [comment]
as mentioned in #96 
```
fetching the modification date of a single file is antithetical to the way git works
since git does not track per-file history. Fetching the date of a single
file is a Slow Operation because it requires scanning global history
looking for a commit in which the desired file was changed.
```

**Review by mcbloch — APPROVED** [review]

**Comment by werthen** [comment]
@mcbloch There's still an issue with this fix. A lot of posts now show an incorrect writing date, such as the following:





I think this should be reverted and reopened.

**Comment by JensTimmerman** [comment]
I things just removing the “created at” part of the pr I made was a good idea. 
It might fix the merge issue but won’t show the correct created date. 

I can look into this later when I have some time. 

Is there a documented way to add test to this repo? So a test can pick up a regression like this?

**Comment by werthen** [comment]
No custom tests yet, but should be easy enough to add using nanoc's checks: <https://nanoc.ws/doc/testing/>

**Comment by JensTimmerman** [comment]
@mcbloch please don’t self review and merge your changes?

**Comment by redfast00** [comment]
@JensTimmerman maybe use the first date the file was created instead of the last time?

**Comment by JensTimmerman** [comment]
@redfast00 can this be discussed in https://github.com/ZeusWPI/zeus.ugent.be/issues/265 ? I have asked a few questions on how you want to see edge cases handled in that issue

**Pull request merged**
