### PR TITLE
Revamp contact

### PR DESCRIPTION
**Pull request by wschella**
PREVIEW LINK: http://198.zeus.werthen.com

Before:
before2

After:
after2

After really:
blue

### CODE REVIEW

**Comment by niknetniko** [comment]
Someone on slack said the icons were a bit light. I don't know if they meant these ones, but I do think they are a bit light. Perhaps we could do something like this?
maybe_this

**Comment by wschella** [comment]
I think we might fix this better by making the circles darker

**Comment by niknetniko** [comment]
Also a good solution

Op 14 okt. 2017 19:36 schreef "Wout Schellaert" <notifications@github.com>:

**Comment by wschella** [comment]
It's blue now, a bit bright, but it's complementary to the zeus orange, and it's clear.

**Pull request merged**
