### PR TITLE
Fixed mobile styling for table

### PR DESCRIPTION
**Pull request by brickmaker17**
screen shot 2018-10-05 at 10 58 48 pm

### CODE REVIEW

**Comment by wschella** [comment]
@brickmaker17 great work already! Would be nice if you are able to create some visual separation between the functions tho.

**Comment by brickmaker17** [comment]
> @brickmaker17 great work already! Would be nice if you are able to create some visual separation between the functions tho.

What do you mean? Would increasing the size of the work Function be good or do you have something else in mind?

**Comment by wschella** [comment]
@brickmaker17 i was thinking of increasing thickness for the lines between functions, or removing the lines between function-name-email

**Comment by wschella** [comment]
But hey, the PR is definitely appreciated, so if you're not interested i'll merge.

**Comment by brickmaker17** [comment]
screen shot 2018-10-05 at 10 58 48 pm
I removed the border. It should be good to merge. Let me know if there are any questions. Thanks

**Pull request merged**
