### PR TITLE
Reports (only includes latest report as well)

### PR DESCRIPTION
**Pull request by werthen**
# TO BE DOCUMENTED

Reports should start analogous to the following format:

```
% Bestuursvergadering 3
% Isaura Claeys
% 21/02/2018 - 17:25
```

See https://pandoc.org/MANUAL.html#metadata-blocks

I don't immediately see a way to make YAML metadata blocks work, as nanoc immediately interprets them.

### CODE REVIEW

**Comment by wschella** [comment]
Are they actually displayed somewhere? Suggestion: we might want to display them in the same place as the blogposts on the frontpage, depending on which is more recent.

**Comment by werthen** [comment]
/about/verslagen, placing on front page is a good suggestion

**Comment by wschella** [comment]
We should specify pandoc is a requirement, certainly cause it can be quite a heavy install.

**Comment by werthen** [comment]
Good point, I'm still looking into a Dockerfile, should make development quite easy.

**Comment by wschella** [comment]
Is that necessary tho? Docker isn't light either, and seems a bit overkill for static site development.

**Comment by wschella** [comment]
Other suggestion: could we make the pdf compilation optional?

**Comment by werthen** [comment]
Yes I thought of that as well, we could compile it only when compiling for production, but it's honestly (for now) not that time consuming, 1 second per pdf roughly (this will add up though)

**Comment by wschella** [comment]
It's not only about compilation time, but also about project setup. If i wan't to change some css on some page i don't need to compile pdf's, and all setup is redundant an can only make things go wrong.

**Pull request merged**
