### PR TITLE
Add DRIVE as a submodule for our meeting reports

### PR DESCRIPTION
**Pull request by rien**

### CODE REVIEW

**Comment by wschella** [comment]
I wonder if the symlink breaks windows builds.
Also, what's up with the failed handshake when Travis clones the submodule?

**Comment by rien** [comment]
@Hannes-Kl you can build the site on windows, could you test this PR and see if the 'verslagen' can be built? 

This should do the trick, I think:
```
git checkout drive-verslagen
git submodule update
bundle exec nanoc --env=prod # Required to also build the reports, may take a while
```

**Comment by rien** [comment]
I will look into the failed handshake, but it's odd...

**Comment by werthen** [comment]
Instead of using a symlink, you can add de verslagen as another data source, like I did for the node_modules folder in nanoc.yaml. No symlink needed

**Comment by rien** [comment]
> @rien Tried building it, but it can't find the verslagen
> 
> Have my crashlog:
> [crash.log](https://github.com/ZeusWPI/zeus.ugent.be/files/2652448/crash.log)

OK symlinks seem to be broken on Windows, I will follow @werthen's suggestion then. Thanks for trying this out!

**Comment by redfast00** [comment]
@rien does this work now?

**Comment by rien** [comment]
Unfortunately, not yet. Doing SSH stuff in Travis is not as straightforward as expected. I will try to look at this again...

**Comment by rien** [comment]
@redfast00 ready for a review and merge!

**Comment by redfast00** [comment]
@rien does not seem to have recent meeting reports (https://301.pr.zeus.gent/about/verslagen/). Is this expected?

**Comment by werthen** [comment]
Could you add a paragraph in the README explaining how someone can pull in the reports? Unless it works automagically, but I assume you'd have to do a `git submodule update --init` or something of the like

**Pull request merged**
