### PR TITLE
Add shell.nix for easy development with nix

### PR DESCRIPTION
**Pull request by rien**
This is of course something OS-specific, so I would understand if you would not want to bloat the repository with this.

### CODE REVIEW

**Comment by mcbloch** [comment]
- `git clone https://github...`
- `cd zeus.ugent.be`
- `nix-shell`
- `bundle install`
- `yarn install`
- `bundle exec nanoc live`

```
[nix-shell:/tmp/zeus.ugent.be]$ bundle exec nanoc live
View the site at http://127.0.0.1:3000/
Puma starting in single mode...
* Puma version: 5.2.1 (ruby 2.6.6-p146) ("Fettisdagsbulle")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 1783
* Listening on http://127.0.0.1:3000
Use Ctrl-C to stop
/tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-cli-4.12.0/lib/nanoc/cli/commands/show-plugins.rb:17: warning: already initialized constant Nanoc::CLI::Commands::ShowPlugins::PLUGIN_CLASS_ORDER
/tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-cli-4.12.0/lib/nanoc/cli/commands/show-plugins.rb:17: warning: previous definition of PLUGIN_CLASS_ORDER was here
/tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-cli-4.12.0/lib/nanoc/cli/commands/show-plugins.rb:22: warning: already initialized constant Nanoc::CLI::Commands::ShowPlugins::PLUGIN_CLASSES
/tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-cli-4.12.0/lib/nanoc/cli/commands/show-plugins.rb:22: warning: previous definition of PLUGIN_CLASSES was here

01:33:02 - ERROR - Compilation failed!

Captain! We’ve been hit!

Nanoc::DataSources::Filesystem::Errors::InvalidEncoding: Could not read data/supporting_members.yaml because the file is not valid US-ASCII.

  0. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem/tools.rb:175:in `rescue in read_file'
  1. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem/tools.rb:172:in `read_file'
  2. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem/parser.rb:36:in `parse_with_separate_meta_filename'
  3. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem/parser.rb:27:in `call'
  4. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem.rb:412:in `parse'
  5. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem.rb:157:in `read_proto_document'
  6. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem.rb:186:in `block in load_objects'
  7. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem.rb:223:in `block (2 levels) in each_content_meta_pair_in'
  8. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem.rb:215:in `each'
  9. /tmp/zeus.ugent.be/vendor/bundle/ruby/2.6.0/gems/nanoc-4.12.0/lib/nanoc/data_sources/filesystem.rb:215:in `block in each_content_meta_pair_in'
  ... 75 lines omitted (see crash.log for details)

A detailed crash log has been written to ./crash.log.
01:33:02 - INFO - Guard is now watching at '/tmp/zeus.ugent.be'
```

**Comment by rien** [comment]
This is weird, when I start a `nix-shell --pure` it gives the same error. So this is missing some kind of dynamically loaded dependency to support UTF-8?

**Comment by rien** [comment]
Adding `glibcLocales` and setting `LANG=en_US.UTF-8` fixed this issue.

**Review by werthen — APPROVED** [review]
I wouldn't mind adding this to the repo. Plenty of Nix users at Zeus :) Just like I wouldn't mind adding a Dockerfile for example

Verified on my own NixOS installation, works like a charm!

**Review by werthen — CHANGES_REQUESTED** [review]
On second thought, this won't work for production. I'm testing out which distribution of Texlive we would need. Maybe we should split it up into a development/basic and a production shell?

**Comment by werthen** [comment]
The extra needed packages would be `pandoc (texlive.combine { inherit (texlive) scheme-small enumitem; })`

Test this with `git submodule update --init --recursive` and `bundle exec nanoc -e prod`

**Review by werthen — APPROVED** [review]

**Pull request merged**
